name: generator-build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-16.04, macos-10.15]

    steps:
    - uses: actions/checkout@v2
    - name: configure macos
      if: matrix.os == 'macos-10.15'
      run: |
        brew update
        brew upgrade llvm
        export CXX="/usr/local/opt/llvm/bin/clang++"
        cmake CMakeLists.txt
    - name: configure ubuntu
      if: matrix.os != 'macos-10.15'
      run: cmake CMakeLists.txt
    - name: make
      run: make
